### ISSUE TITLE
Fix Assert.Fail and Assert.Inconclusive

### ISSUE THREAD

**Issue by jschneidereit** [jschneidereit/MsTestToXunitConverter#8]
These don't have equivalents in xUnit... 

Assert.Fail could be `Assert.True(false, "message");`

Assert.Inconclusive should probably just get commented out... with a TODO so the visual studio task list will pick it up

**Comment by RikkiGibson** [comment]
I vote for `Assert.False(true, message);`
:P

**Comment by jschneidereit** [comment]
I agree for `Fail()`. Do you think `Inconclusive()` should fail too? 

I guess failing for inconclusive is fair, and the user can investigate the new failure and figure out what they want to do with that test...

**Comment by jschneidereit** [comment]
Fixed in b7df7d6 and df64052
